services:
 # the Database
 db:
  image: postgres:16-alpine
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: password
   POSTGRES_DB: pfe_tracker
  ports:
    - "5432:5432"

 # the Automation Service
 n8n:
  image: n8nio/n8n
  ports:
   - "5678:5678"
  environment:
    - N8N_HOST=localhost
  volumes:
    - ./n8n_data:/home/node/.n8n

volumes:
  n8n_data: